[theme]
primaryColor = "#4CAF50"               # Grüner Farbton als primäre Farbe
backgroundColor = "#FFFFFF"            # Weißer Hintergrund
secondaryBackgroundColor = "#F5F5F5"  # Hellgrauer Sekundärhintergrund
textColor = "#000000"                  # Schwarzer Text
font = "sans serif"                    # Standard-Schriftart

[server]
headless = true                        # Server läuft im headless-Modus
port = 8501                            # Standardport für Streamlit
enableCORS = false                     # CORS deaktivieren, um lokale Zugriffe zu erlauben
